// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetfirst.Data;

namespace aspnetfirst.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20191019071227_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("aspnetfirst.Models.Players.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Expirience");

                    b.Property<string>("Name");

                    b.Property<int>("Skill");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId");

                    b.ToTable("players");

                    b.HasData(
                        new { PlayerId = -1, Expirience = 85, Name = "Ronaldo", Skill = 95, TeamId = 1 },
                        new { PlayerId = -2, Expirience = 79, Name = "Messi", Skill = 93, TeamId = 2 },
                        new { PlayerId = -3, Expirience = 79, Name = "Robinho", Skill = 76, TeamId = 3 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
