// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetfirst.Data;

namespace aspnetfirst.Migrations.Team
{
    [DbContext(typeof(TeamContext))]
    partial class TeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("aspnetfirst.Models.Players.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Expirience");

                    b.Property<string>("Name");

                    b.Property<int>("Skill");

                    b.Property<int>("TeamId");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("aspnetfirst.Models.Teams.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Coach");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("TotalExperience");

                    b.Property<int>("TotalSkill");

                    b.HasKey("TeamId");

                    b.ToTable("players");

                    b.HasData(
                        new { TeamId = 1, Coach = "Dias", Description = "Italian club", Name = "Juventus", TotalExperience = 0, TotalSkill = 0 },
                        new { TeamId = 2, Coach = "Moriis", Description = "Spain club", Name = "Barcelona", TotalExperience = 0, TotalSkill = 0 },
                        new { TeamId = 3, Coach = "Moriis", Description = "Spain club", Name = "Barcelona", TotalExperience = 0, TotalSkill = 0 }
                    );
                });

            modelBuilder.Entity("aspnetfirst.Models.Players.Player", b =>
                {
                    b.HasOne("aspnetfirst.Models.Teams.Team")
                        .WithMany("players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
